### ISSUE TITLE
Can't use this hash

### ISSUE THREAD

**Issue by Manther** [ms-ati/docile#18]
Can't do this:

variable PARAMETER_VARIABLE.create {
          name :bar
          value {:alpha => {:default => 1}, :beta => {:default => 2}, :charlie => {:default => 3}, :delta => {:default => 4}}
        }

  

for something like this:

class Parameter 
          attr_reader :name

          def initialize(name, metadata)
            @name = name
            super({:name => name, :metadata => metadata})
          end

          def Parameter.create(&block)
            Docile.dsl_eval(ParameterBuilder.new, &block).create
          end
        end

        class ParameterBuilder
          def name(name)
            @name = name
          end

          def value(value)
            if value.is_a? Hash
              @value = {:child => value}
            elsif value.is_a? Array
              @value = {:default => value}
            else
              @value = value
            end
          end

          def create
            Parameter.new(@name, @value)
          end
        end

**Comment by ms-ati** [comment]
Hi there, thanks for reporting an issue. Before I look at this, would you consider editing the issue so that the code blocks are both formatted correctly, and are accurate in that I can execute them without guessing and editing?

Thanks in advance, happy to help.

**Comment by Manther** [comment]
And here's the error

**Comment by Manther** [comment]
https://gist.github.com/Manther/408330f61087cde95d23

**Comment by ms-ati** [comment]
Ok, since you did not, I went ahead and modified your gist so that it uses correct Ruby syntax and can be run in `irb`:

https://gist.github.com/ms-ati/e5b4b3e862ebc858b152

I am seeing that this works on my end. Can you please check on your end?

**Comment by ms-ati** [comment]
Hi @Manther, did you have a chance to see if my gist above addresses the usage here?

**Comment by Manther** [comment]
Yes sorry, syntax error on my parts. Closing.

**Comment by ms-ati** [comment]
Excellent!
