### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by lohqua** [ms-ati/docile#19]
The examples make it look easy but they are all examples when the DSL code lives in the same file as the DSL implementation, which is hardly useful.

How would I actually run it if
@sauce_level = :extra

pizza do
  cheese
  pepperoni
  sauce @sauce_level
end

was in a separate file from the rest?

**Comment by ms-ati** [comment]
Not sure I 100% understand -- you mean using `require 'other_file.rb'`?

**Comment by lohqua** [comment]
in my_order.rb

@sauce_level = :extra

pizza do
cheese
pepperoni
sauce @sauce_level
end

in pizza_builder.rb

Pizza = Struct.new(:cheese, :pepperoni, :bacon, :sauce)

class PizzaBuilder
  def cheese(v=true); @cheese = v; self; end
  def pepperoni(v=true); @pepperoni = v; self; end
  def bacon(v=true); @bacon = v; self; end
  def sauce(v=nil); @sauce = v; self; end
  def build
    Pizza.new(!!@cheese, !!@pepperoni, !!@bacon, @sauce)
  end
end

PizzaBuilder.new.cheese.pepperoni.sauce(:extra).build

in pizza_dsl.rb

def pizza(&block)
  Docile.dsl_eval(PizzaBuilder.new, &block).build
end

Would my_order.rb contain the requires? It is not clear how this would be run.

**Comment by ms-ati** [comment]
Ah I see. This doesn't sound like a Docile question as much as a Ruby language question, right?

I've taken you example above, and made a gist for it that works, here:
https://gist.github.com/ms-ati/faa78ca655b3ff7fc4ec

**Comment by lohqua** [comment]
That is where I got confused. I am looking to create an actual DSL where the DSL loads and drives the my_order.rb file. 

Like bundler, rspec or rake instead of just a Ruby program that relies on bundler.

Instead of a typical ruby program that is run like:
ruby name_of_ruby_file 
or worse:
bundle exec ruby -I. my_order.rb 

I was wanting to do: pizza my_order.pz.

 Like an actual DSL.

Is that possible with Docile or do I just need to roll my own?

**Comment by ms-ati** [comment]
Hi @lohqua I'll make a deal with you. If you can specify clearly, and in enough detail to make sense, what you want to achieve, then I'll be happy to help. Is that fair?

**Comment by lohqua** [comment]
I am not sure what was confusing about my last post. I will try to simplify it down.

Rake is a DSL. Right?

It is run like so: rake <task name>.

Not ruby rake.rb <task name>

That should be crystal clear.

If not let's go with gem. That is also a DSL.

It is invoked like so:

gem install <name of gem>

not ruby gem.rb install <gem>

Right?

A real DSL drives the files containing code written in the DSL format. The file written in the DSL file does not drive the DSL. Putting require 'pizza_dsl' in my_order.rb is as stupid and backwards as putting require 'ruby' in a ruby file. It needs to go away since pizza_dsl.rb should get my_order.rb passed to it.

Does that make sense?

Let's pretend I want a pizza DSL.

I want my_order.rb to be named my_order.pz.

Got that?

I want pizza_dsl.rb to be invoked by pizza. Since it is a DSL, pizza will drive the order.

So putting it together, to to run my_order I want this on the command line:

pizza my_order.pz

Which is equivalent to:

rake <rake task>

Where pizza is the DSL just like rake is.

What you have in your gist is a very convoluted *ruby* program. 

What I am looking for is the ability to create a *pizza* DSL.

I am not sure how much more I can dumb down the question, so I hope this makes it clear. I want to create a real DSL with docile. Is that possible?

Can you please show me a gist where this would order the pizza:

pizza my_order.pz

**Comment by ms-ati** [comment]
Ah. Ok, I see. The act of creating an executable which reads a file written
in the DSL (domain specific language) is beyond the scope of Docile at
present.

What you want to do is to write an executable which feeds the contents of s
file to a DSL interpreter, I think.



On Thursday, December 24, 2015, lohqua <notifications@github.com> wrote:

> I am not sure what was confusing about my last post. I will try to
> simplify it down.
>
> Rake is a DSL. Right?
>
> It is run like so: rake .
>
> Not ruby rake.rb
>
> That should be crystal clear.
>
> If not let's go with gem. That is also a DSL.
>
> It is invoked like so:
>
> gem install
>
> not ruby gem.rb install
>
> Right?
>
> A real DSL drives the files containing code written in the DSL format. The
> file written in the DSL file does not drive the DSL. Putting require
> 'pizza_dsl' in my_order.rb is as stupid and backwards as putting require
> 'ruby' in a ruby file. It needs to go away since pizza_dsl.rb should get
> my_order.rb passed to it.
>
> Does that make sense?
>
> Let's pretend I want a pizza DSL.
>
> I want my_order.rb to be named my_order.pz.
>
> Got that?
>
> I want pizza_dsl.rb to be invoked by pizza. Since it is a DSL, pizza will
> drive the order.
>
> So putting it together, to to run my_order I want this on the command line:
>
> pizza my_order.pz
>
> Which is equivalent to:
>
> rake
>
> Where pizza is the DSL just like rake is.
>
> What you have in your gist is a very convoluted *ruby* program.
>
> What I am looking for is the ability to create a *pizza* DSL.
>
> I am not sure how much more I can dumb down the question, so I hope this
> makes it clear. I want to create a real DSL with docile. Is that possible?
>
> Can you please show me a gist where this would order the pizza:
>
> pizza my_order.pz
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ms-ati/docile/issues/19#issuecomment-167161478>.
>


-- 
Marc Siegel
Technology Specialist
American Technology Innovations

Email: marc@usainnov.com
Phone: 1 (617) 399-8145
Cell: 1 (617) 223-1220
Fax: 1 (617) 334-7975

**Comment by lohqua** [comment]
It doesn't have to be a executable per se. A ruby file with a shebang line. That really wasn't the problem.

This real issue is that require 'pizza_dsl' in `my_order.rb` absolutely doesn't belong there.

I found some tutorials on how to write real DSL's so I will go that direction. I will see if I can generalize it so it can be used like Docile.

Thanks for your time, patients and happy holidays.
