### ISSUE TITLE
method_missing': [DEPRECATION] #load_adapter is deprecated. Use #load_profile instead

### ISSUE THREAD

**Issue by BjornMelgaard** [ms-ati/docile#20]
```
/usr/lib/ruby/gems/2.3.0/gems/docile-1.1.5/lib/docile/fallback_context_proxy.rb:57:in `method_missing': [DEPRECATION] #load_adapter is deprecated. Use #load_profile instead.
```

**Comment by ms-ati** [comment]
Hi, @BjornMelgaard, as you can see in [fallback_context_proxy.rb:57](https://github.com/ms-ati/docile/blob/master/lib/docile/fallback_context_proxy.rb#L57), there is no call to any `#load_adapter` method. Rather, the deprecation warning is probably for whatever code is being called _as a DSL_ via the Docile library.

Does that help? Do you know what code is actually calling this deprecated `#load_adapter` method?

**Comment by BjornMelgaard** [comment]
I think this called from [simplecov](https://github.com/colszowka/simplecov/blob/master/lib/simplecov.rb#L142)
But why line from your gem? Maybe I disturb you in vain  :confused:

**Comment by ms-ati** [comment]
Hi @BjornMelgaard -- yes, you've tracked down where it is coming from, inside SimpleCov. In your simplecov configuration, you are using Docile for the DSL as that is used by SimpleCov. So when you call the method `#load_adapter`, the DEPRECATED message is being reported at the place it's called in the DSL, instead of where the DSL call is made

**Comment by ms-ati** [comment]
In other words, search your code for `load_adapter` ;)

**Comment by ms-ati** [comment]
I don't know if it's possible to improve this situation. But I will research of Docile could cause the `Kernel#warn` to report the original call site instead

**Comment by ms-ati** [comment]
Closing this in favor of fixing in SimpleCov: https://github.com/colszowka/simplecov/issues/504
