### ISSUE TITLE
Question about use of DSL object's private method

### ISSUE THREAD

**Issue by taichi-ishitani** [ms-ati/docile#32]
Hi @ms-ati ,

I have a question about use of DSL object's private method.

I tried to call DLS object's private methods via `Docile.dsl_eval` but I got NoMethodError.
Here is a small script to reproduce this problem.

```ruby
require 'docile'
class Foo
  private
  def foo; end
end
Docile.dsl_eval(Foo.new) { foo } # => NoMethodError (undefined method `foo' for main:Object)
```

Is this correct behavior?
If you think that DSL methods should be public then I think this is correct behavior.
If you think that `Docile.dsl_eval` should behave like `#instance_eval` then I think this problem should be resolved.

**Comment by ms-ati** [comment]
Hi @taichi-ishitani thank you for using the library and asking this question!

My current view is:
(a) this is desired behavior
(b) it should be documented and covered by tests

I'd be interested in understanding the motivation for private methods of the DSL object to be accessible? That doesn't seem like an ideal usage pattern for this library to be encouraging?

**Comment by taichi-ishitani** [comment]
Hi @ms-ati ,
Thanks for your comment and I understand your thought.

> the motivation for private methods of the DSL object to be accessible

My motivation is rather than for alternate of `#instance_eval`.
I often use `Docile.dsl_eval` instead of `#instance_eval` because both of receiver's methods and block context's methods can be used so I'd like `Docile.dsl_eval` to behave like '#instance_eval' for this use case . Therefore, I asked you this question.

**Comment by taichi-ishitani** [comment]
Hi @ms-ati ,

This ticket is just to confirm your view.
Now, I understand your view so I'm closing this ticket.
