### ISSUE TITLE
Warning related to key word argument

### ISSUE THREAD

**Issue by taichi-ishitani** [ms-ati/docile#44]
Hi @ms-ati ,

Following warning related to key word argument is displayed when an method including key word argument is called withing DSL block.

```
/opt/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/docile-1.3.2/lib/docile/fallback_context_proxy.rb:87: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

Execute this example code  then you will see the above warning.

```ruby
class Foo
  def bar(baz: 0)
  end
end

require 'docile'
Docile.dsl_eval(Foo.new) do
  bar(baz: 1)
end
```

* Ruby version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
* Docile version: 1.3.2

**Comment by ms-ati** [comment]
Thank you for creating this issue @taichi-ishitani 

How would you like to proceed? Are you planning or currently working on a pull request, or shall I look into it myself?

**Comment by taichi-ishitani** [comment]
I open a PR (#45) for this issue.

**Comment by taichi-ishitani** [comment]
Thank you for merging #45 !
