### ISSUE TITLE
Is ruby2_keywords also required here?

### ISSUE THREAD

**Issue by jochenseeber** [ms-ati/docile#56]
#52 fixed keyword argument delegation (learned something new, thanks!)

Do we also need this here (cc @eregon)? https://github.com/ms-ati/docile/blob/4300547ffe12038a3fd471fe408bcf4ca6b6eb70/lib/docile/fallback_context_proxy.rb#L55

**Comment by eregon** [comment]
Yes, it's also needed, if the method called by `receiver.__send__(method.to_sym, *args, &block)` has keyword arguments.

It's a good idea to review all usages of rest arguments (e.g., `*args`) that are used for delegation, and might potentially call a method which has keyword arguments. In that case, `ruby2_keywords` should be used to correctly pass keyword arguments as-is, and not transforming them back to a positional Hash argument.

**Comment by ms-ati** [comment]
cc @jochenseeber @eregon and others, if you'd consider proposing a PR to address this It would be greatly appreciated and welcome! :)

**Comment by jochenseeber** [comment]
I can try and create a PR, but it will be 2 weeks before I have time.

**Comment by ms-ati** [comment]
@jochenseeber is this closed by #62 ?

**Comment by ms-ati** [comment]
@jochenseeber @eregon I'm going to mark this closed by #62 -- please do feel free to re-open this issue if I've misunderstood and it's not fixed.

Also, I've just released v1.3.5 to Rubygems with these changes!
